export const toolCatalog = [
	{
		name: "Bookmark",
		status: "Ready",
		description: "Synced collections and links for your browser start page.",
		href: "/",
		icon: "PanelsTopLeft",
		authRequired: true,
	},
	{
		name: "Date converter",
		status: "Ready",
		description: "ISO, UTC, local time, Unix seconds, and Unix milliseconds.",
		href: "/date-converter",
		icon: "Calendar",
	},
	{
		name: "Thai name generator",
		status: "Ready",
		description: "Random Thai first name, last name, and nickname.",
		href: "/thai-name-generator",
		icon: "User",
	},
	{
		name: "JSON formatter",
		status: "Ready",
		description: "Pretty-print or minify JSON with explicit actions.",
		href: "/json-formatter",
		icon: "FileJson",
	},
	{
		name: "Financial planner",
		status: "Ready",
		description: "Budget snapshots, income tracking, and monthly planning.",
		href: "/financial-planner",
		icon: "Wallet",
		authRequired: true,
		children: [
			{ name: "Dashboard", href: "/financial-planner/dashboard" },
			{ name: "Planner", href: "/financial-planner" },
			{ name: "Credit Card Master", href: "/financial-planner/credit-card-master" },
		],
	},
	{
		name: "Installment logs",
		status: "Soon",
		description: "Track active payments and remaining balances.",
		href: null,
		icon: "History",
	},
];
